apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: shop
data:
  init.sql: |
    CREATE DATABASE order_db;
    CREATE DATABASE inventory_db;
    CREATE DATABASE delivery_db;

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: shop
type: Opaque
stringData:
  POSTGRES_USER: starlabs
  POSTGRES_PASSWORD: bootcamp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init
          configMap:
            name: postgres-init

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: shop
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: db
